[workspace]
members = ["compiler/w"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[dev-dependencies]
#criterion = "0.3"


#[dependencies]

#[dev-dependencies]
#similar = "2.0.0"
