[package]
name = "w_session"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
unicode-segmentation = "1.8"
w_lexer = { path = "../w_lexer" }
w_parser = { path = "../w_parser" }
w_errors = { path = "../w_errors" }
