[package]
name = "w_compiler"
version = "0.0.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
w_lexer = { path = "../w_lexer" }
w_codegen = { path = "../w_codegen" }
w_errors = { path = "../w_errors" }
w_utils = { path = "../w_utils" }
