on: [push, pull_request, workflow_dispatch]
name: Tests & Coverage

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast --verbose
        env:
          RUSTFLAGS: "-Zinstrument-coverage"
          RUSTDOCFLAGS: "-Zinstrument-coverage"
          LLVM_PROFILE_FILE: "w-%p-%m.profraw"
      - run: |
        cargo install grcov
        grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - uses: codecov/codecov-action@v1
        with:
          files: lcov.info
          flags: unittests
          fail_ci_if_error: true
          verbose: true
